; ---------------------------------------------------------------------------- ;
;                                    Content                                   ;
; ---------------------------------------------------------------------------- ;

[11]
Meter=Shape
Y=(#Sec.P#)
MeterStyle=Div:S
[1]
Meter=String
MeterStyle=String:S
Text=To-do
[12]
Meter=Shape
MeterStyle=Div:S
[2]
Meter=String
MeterStyle=String:S
Text=Poll
[13]
Meter=Shape
MeterStyle=Div:S
[3]
Meter=String
MeterStyle=String:S
Text=Left click to select
[14]
Meter=Shape
MeterStyle=Div:S
[4]
Meter=String
MeterStyle=String:S
Text=Right click to rename
[15]
Meter=Shape
MeterStyle=Div:S
[5]
Meter=String
MeterStyle=String:S
Text=Testing ground
