[Bool2]
Meter=Shape
Y=((70+30*1)*#Scale#)
MeterStyle=Stroke:S
[Line2]
Meter=String
MeterStyle=String:S | Note:S
[Bool3]
Meter=Shape
Y=((70+30*2)*#Scale#)
MeterStyle=Stroke:S
[Line3]
Meter=String
MeterStyle=String:S | Note:S
[Bool4]
Meter=Shape
Y=((70+30*3)*#Scale#)
MeterStyle=Stroke:S
[Line4]
Meter=String
MeterStyle=String:S | Note:S
[Bool5]
Meter=Shape
Y=((70+30*4)*#Scale#)
MeterStyle=Stroke:S
[Line5]
Meter=String
MeterStyle=String:S | Note:S
[Bool6]
Meter=Shape
Y=((70+30*5)*#Scale#)
MeterStyle=Stroke:S
[Line6]
Meter=String
MeterStyle=String:S | Note:S
[Bool7]
Meter=Shape
Y=((70+30*6)*#Scale#)
MeterStyle=Stroke:S
[Line7]
Meter=String
MeterStyle=String:S | Note:S
[Bool8]
Meter=Shape
Y=((70+30*7)*#Scale#)
MeterStyle=Stroke:S
[Line8]
Meter=String
MeterStyle=String:S | Note:S
[Bool9]
Meter=Shape
Y=((70+30*8)*#Scale#)
MeterStyle=Stroke:S
[Line9]
Meter=String
MeterStyle=String:S | Note:S
[Bool10]
Meter=Shape
Y=((70+30*9)*#Scale#)
MeterStyle=Stroke:S
[Line10]
Meter=String
MeterStyle=String:S | Note:S
[Bool11]
Meter=Shape
Y=((70+30*10)*#Scale#)
MeterStyle=Stroke:S
[Line11]
Meter=String
MeterStyle=String:S | Note:S
[Bool12]
Meter=Shape
Y=((70+30*11)*#Scale#)
MeterStyle=Stroke:S
[Line12]
Meter=String
MeterStyle=String:S | Note:S
[Bool13]
Meter=Shape
Y=((70+30*12)*#Scale#)
MeterStyle=Stroke:S
[Line13]
Meter=String
MeterStyle=String:S | Note:S
[Bool14]
Meter=Shape
Y=((70+30*13)*#Scale#)
MeterStyle=Stroke:S
[Line14]
Meter=String
MeterStyle=String:S | Note:S
[Bool15]
Meter=Shape
Y=((70+30*14)*#Scale#)
Shape=Line 0,(25*#scale#),(#W#-#P#*2),(25*#scale#) | StrokeWidth 0
MeterStyle=Stroke:S
[Line15]
Meter=String
MeterStyle=String:S | Note:S
