[Bool2]
Meter=Shape
MeterStyle=Stroke:S
[Line2]
Meter=String
MeterStyle=String:S | Note:S
[Bool3]
Meter=Shape
MeterStyle=Stroke:S
[Line3]
Meter=String
MeterStyle=String:S | Note:S
[Bool4]
Meter=Shape
MeterStyle=Stroke:S
[Line4]
Meter=String
MeterStyle=String:S | Note:S
[Bool5]
Meter=Shape
MeterStyle=Stroke:S
[Line5]
Meter=String
MeterStyle=String:S | Note:S
[Bool6]
Meter=Shape
MeterStyle=Stroke:S
[Line6]
Meter=String
MeterStyle=String:S | Note:S
[Bool7]
Meter=Shape
MeterStyle=Stroke:S
[Line7]
Meter=String
MeterStyle=String:S | Note:S
[Bool8]
Meter=Shape
Shape=Line 0,(25*#scale#),(#W#-#P#*2),(25*#scale#) | StrokeWidth 0
MeterStyle=Stroke:S
[Line8]
Meter=String
MeterStyle=String:S | Note:S
[AddButton]
Meter=Shape
MeterStyle=AddButton:S
[AddString]
Meter=String
MEterStyle=String:S | AddString:S
[RemButton]
Meter=Shape
MeterStyle=RemButton:S
[RemString]
Meter=String
MEterStyle=String:S | RemString:S
