[Variables]
Scale=1
UseHotkey=1

DragAmount=1
ScreenPadding=30

Animation=1
TweenTime1=1000

FontFace=Poppins
IconName=Todo
AutoNextLine=0
CheckDots=1

Maincolor=12,12,12
SecColor=242, 52, 0, 50
StrokeColor=30,30,30
FontColor=242,240,255
AccentColor=242, 52, 0
BoolColor=242, 52, 0

rows=8

; ---------------------------------------------------------------------------- ;
;                                     Notes                                    ;
; ---------------------------------------------------------------------------- ;



Line1=Chinese homework
LIne2=Buy lab coat
Line3=Clean up the side table
Line4=
Line5=
Line6=
Line7=
Line8=English Scrap book
Line9=
Line10=
Line11=
Line12=
Line13=
Line14=
Line15=
Line16=
Line17=
Line18=
Line19=
Line20=
